@startuml
set separator none
title karp-backend - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
System(sbauth, "sb-auth", $descr="Språkbanken's Auth service", $tags="", $link="../../sb-auth/context/")
System(karplexcore, "karp-lex-core", $descr="Public commands, value objects and data transfer objects for karp.lex", $tags="", $link="../../karp-lex-core/context/")
Person(User, "User", $descr="", $tags="", $link="")
Person(Admin, "Admin", $descr="", $tags="", $link="")
Person(Machine, "Machine", $descr="machine", $tags="", $link="")
System(karpbackend, "karp-backend", $descr="", $tags="", $link="../container/")

Rel_D(User, karpbackend, "Uses", $techn="", $tags="", $link="")
Rel_D(Machine, karpbackend, "Uses", $techn="", $tags="", $link="")
Rel_D(Admin, karpbackend, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend, karplexcore, "", $techn="", $tags="", $link="")
Rel_D(karpbackend, sbauth, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml