#!/usr/bin/env python3

# WARNING: CAVEAT UTILITOR
#
#  This file was automatically generated by TatSu.
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.

# ruff: noqa: RUF100, C405, COM812, I001, F401, PLR1702, PLC2801, SIM117

import sys
from pathlib import Path

from tatsu.buffering import Buffer
from tatsu.parsing import Parser
from tatsu.parsing import tatsumasu
from tatsu.parsing import leftrec, nomemo, isname
from tatsu.infos import ParserConfig
from tatsu.util import re, generic_main


KEYWORDS: set[str] = set()


class KarpQueryBuffer(Buffer):
    def __init__(self, text, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=None,
            eol_comments=None,
            keywords=KEYWORDS,
            start='start',
        )
        config = config.replace(**settings)

        super().__init__(text, config=config)


class KarpQueryParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=None,
            eol_comments=None,
            keywords=KEYWORDS,
            start='start',
        )
        config = config.replace(**settings)

        super().__init__(config=config)

    @tatsumasu()
    def _start_(self):
        self._expression_()
        self._check_eof()

    @tatsumasu()
    def _expression_(self):
        with self._choice():
            with self._option():
                self._logical_expression_()
            with self._option():
                self._query_expression_()
            with self._option():
                self._sub_query_()
            self._error(
                'expecting one of: '
                '<and> <binary_query_expression>'
                '<identifier> <logical_expression> <not>'
                '<or> <query_expression> <sub_query>'
                '<unary_query_expression>'
            )

    @tatsumasu()
    def _query_expression_(self):
        with self._choice():
            with self._option():
                self._unary_query_expression_()
            with self._option():
                self._binary_query_expression_()
            self._error(
                'expecting one of: '
                '<any_arg_expr> <binary_query_expression>'
                '<field_query> <freetext> <text_arg_expr>'
                '<unary_query_expression>'
            )

    @tatsumasu()
    def _unary_query_expression_(self):
        with self._choice():
            with self._option():
                self._field_query_()
            with self._option():
                self._freetext_()
            self._error(
                'expecting one of: '
                "'exists' 'freetext' 'missing'"
                '<field_query>'
            )

    @tatsumasu('FieldQuery')
    def _field_query_(self):
        with self._group():
            with self._choice():
                with self._option():
                    self._token('exists')
                with self._option():
                    self._token('missing')
                self._error(
                    'expecting one of: '
                    "'exists' 'missing'"
                )
        self.name_last_node('op')
        self._token('|')
        self._identifier_()
        self.name_last_node('field')
        self._define(['field', 'op'], [])

    @tatsumasu()
    def _binary_query_expression_(self):
        with self._choice():
            with self._option():
                self._text_arg_expr_()
            with self._option():
                self._any_arg_expr_()
            self._error(
                'expecting one of: '
                '<any_arg_expr> <any_arg_op>'
                '<text_arg_expr> <text_value_op>'
            )

    @tatsumasu('TextArgExpression')
    def _text_arg_expr_(self):
        self._text_value_op_()
        self.name_last_node('op')
        self._token('|')
        self._identifier_()
        self.name_last_node('field')
        self._token('|')
        self._string_value_()
        self.name_last_node('arg')
        self._define(['arg', 'field', 'op'], [])

    @tatsumasu()
    def _text_value_op_(self):
        with self._choice():
            with self._option():
                self._token('contains')
            with self._option():
                self._token('endswith')
            with self._option():
                self._token('regexp')
            with self._option():
                self._token('startswith')
            self._error(
                'expecting one of: '
                "'contains' 'endswith' 'regexp'"
                "'startswith'"
            )

    @tatsumasu('AnyArgExpression')
    def _any_arg_expr_(self):
        self._any_arg_op_()
        self.name_last_node('op')
        self._token('|')
        self._identifier_()
        self.name_last_node('field')
        self._token('|')
        self._any_value_()
        self.name_last_node('arg')
        self._define(['arg', 'field', 'op'], [])

    @tatsumasu()
    def _any_arg_op_(self):
        with self._choice():
            with self._option():
                self._token('equals')
            with self._option():
                self._token('gt')
            with self._option():
                self._token('gte')
            with self._option():
                self._token('lt')
            with self._option():
                self._token('lte')
            self._error(
                'expecting one of: '
                "'equals' 'gt' 'gte' 'lt' 'lte'"
            )

    @tatsumasu()
    def _logical_expression_(self):
        with self._choice():
            with self._option():
                self._and_()
            with self._option():
                self._or_()
            with self._option():
                self._not_()
            self._error(
                'expecting one of: '
                "'and' 'not' 'or'"
            )

    @tatsumasu('SubQuery')
    def _sub_query_(self):
        self._identifier_()
        self.name_last_node('field')
        self._token('(')
        self._expression_()
        self.name_last_node('exp')
        self._token(')')
        self._define(['exp', 'field'], [])

    @tatsumasu('And')
    def _and_(self):
        self._token('and')
        self._token('(')

        def sep0():
            self._token('||')

        def block1():
            self._expression_()
        self._gather(block1, sep0)
        self.name_last_node('@')
        self._token(')')

    @tatsumasu('Freetext')
    def _freetext_(self):
        self._token('freetext')
        self._token('|')
        self._string_value_()
        self.name_last_node('arg')
        self._define(['arg'], [])

    @tatsumasu('Not')
    def _not_(self):
        self._token('not')
        self._token('(')

        def sep0():
            self._token('||')

        def block1():
            self._expression_()
        self._positive_gather(block1, sep0)
        self.name_last_node('@')
        self._token(')')

    @tatsumasu('Or')
    def _or_(self):
        self._token('or')
        self._token('(')

        def sep0():
            self._token('||')

        def block1():
            self._expression_()
        self._gather(block1, sep0)
        self.name_last_node('@')
        self._token(')')

    @tatsumasu()
    def _any_value_(self):
        with self._choice():
            with self._option():
                self._integer_value_()
            with self._option():
                self._string_value_()
            self._error(
                'expecting one of: '
                '<integer_value> <quoted_string_value>'
                '<string_value> <unquoted_string_value>'
                '\\d+$'
            )

    @tatsumasu('StringValue')
    def _string_value_(self):
        with self._choice():
            with self._option():
                self._unquoted_string_value_()
            with self._option():
                self._quoted_string_value_()
            self._error(
                'expecting one of: '
                '\'"\' <quoted_string_value>'
                '<unquoted_string_value> [^|)("]+'
            )

    @tatsumasu()
    def _unquoted_string_value_(self):
        self._pattern('[^|)("]+')
        self.name_last_node('@')

    @tatsumasu('QuotedStringValue')
    def _quoted_string_value_(self):
        self._token('"')

        def block0():
            with self._choice():
                with self._option():
                    self._pattern('(?s)\\s+')
                with self._option():
                    self._token('\\"')
                with self._option():
                    self._pattern('[^"]')
                self._error(
                    'expecting one of: '
                    '\'\\\\"\' (?s)\\s+ [^"]'
                )
        self._closure(block0)
        self.name_last_node('@')
        self._token('"')

    @tatsumasu('int')
    def _integer_value_(self):
        self._pattern('\\d+$')

    @tatsumasu('Identifier')
    def _identifier_(self):
        self._pattern('[^|)(]+')


def main(filename, **kwargs):
    if not filename or filename == '-':
        text = sys.stdin.read()
    else:
        text = Path(filename).read_text()
    parser = KarpQueryParser()
    return parser.parse(
        text,
        filename=filename,
        **kwargs,
    )


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, KarpQueryParser, name='KarpQuery')
    data = asjson(ast)
    print(json.dumps(data, indent=2))

