site_name: Karp Backend
theme: material
nav:
  - Home: index.md
  - Tutorials:
      - "Tutorials": tutorials.md
      - "Add Resource": tutorials/add-resource.md
      - "Create Resource Config": tutorials/create-resource-config.md
  - Development: development.md
  - About:
      - "Release Notes": release-notes.md

repo_name: spraakbanken/karp-backend
repo_url: https://github.com/spraakbanken/karp-backend

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.snippets
