resource_id: municipalities
resource_name: Kommuner i Sverige
fields:
  name: {type: string, required: true}
  state: {type: string}
  region: {type: string}
  capital: {type: string}
  area:
    type: object
    fields:
      total: {type: number}
      land: {type: number}
      water: {type: number}
      city: {type: number}
  population:
    type: object
    fields:
      value:
        type: object
        fields:
          total: {type: integer}
          city: {type: integer}
      density:
        type: object
        fields:
          total: {type: number}
          city: {type: number}
  code: {type: integer, required: true}
  link: {type: string}
sort: name
protected: {read: true}
id: code
