resource_id: places
resource_name: Platser i Sverige
fields:
  name: {type: string, required: true}
  municipality: {collection: true, type: integer, required: true}
  _municipality:
    collection: true
    virtual: true
    plugin: link
    field_params: {id: municipality}
    params: {resource: municipalities, target: code}
    flatten_params: true
  larger_place: {type: integer}
  population: {type: integer}
  area: {type: integer}
  density: {type: integer}
  code: {type: integer, required: true}
  str_collection: {type: string, collection: true}
sort: name
id: code
