# Enable flake8-bugbear (`B`) rules.
select = [
  "A",
  "ANN",
  "B",
  "BLE",
  "C4",
  "C90",
  "D",
  "E", 
  "F",
  # "FBT",
  "I",
  "RUF",
  "S",
  "YTT",
]

# Never enforce `E501` (line length violations).
ignore = ["E501","ANN001","ANN101", "ANN102","B008","D203", "D213","D104"]

line-length = 97

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402", "F401"]
"src/karp/tests/*" = ["D", "S101"]
"src/karp/tests/unit/test_morphological_entry.py" = ["F841", "F821"]
# "src/karp/karp_v6_api/routes/resources_api.py" = ["B008"]
