#!/usr/bin/env python

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.

from __future__ import annotations

from typing import Any
from dataclasses import dataclass

from tatsu.objectmodel import Node
from tatsu.semantics import ModelBuilderSemantics


@dataclass(eq=False)
class ModelBase(Node):
    pass


class KarpQueryModelBuilderSemantics(ModelBuilderSemantics):
    def __init__(self, context=None, types=None):
        types = [
            t for t in globals().values()
            if type(t) is type and issubclass(t, ModelBase)
        ] + (types or [])
        super().__init__(context=context, types=types)


@dataclass(eq=False)
class FieldQuery(ModelBase):
    field: Any = None
    op: Any = None


@dataclass(eq=False)
class BinaryQueryExpression(ModelBase):
    pass


@dataclass(eq=False)
class SubQuery(ModelBase):
    exp: Any = None
    field: Any = None


@dataclass(eq=False)
class And(ModelBase):
    pass


@dataclass(eq=False)
class Freetext(ModelBase):
    arg: Any = None


@dataclass(eq=False)
class Not(ModelBase):
    pass


@dataclass(eq=False)
class Or(ModelBase):
    pass


@dataclass(eq=False)
class StringValue(ModelBase):
    pass


@dataclass(eq=False)
class QuotedStringValue(ModelBase):
    pass


@dataclass(eq=False)
class Identifier(ModelBase):
    pass

