@startuml
set separator none
title karp-backend - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(karplexcore, "karp-lex-core", $descr="Public commands, value objects and data transfer objects for karp.lex", $tags="", $link="")
System(sbauth, "sb-auth", $descr="Språkbanken's Auth service", $tags="", $link="")
Person(User, "User", $descr="", $tags="", $link="")
Person(Admin, "Admin", $descr="", $tags="", $link="")
Person(Machine, "Machine", $descr="machine", $tags="", $link="")

System_Boundary("karpbackend_boundary", "karp-backend", $tags="") {
  AddBoundaryTag("application", $borderColor="#cccccc", $fontColor="#cccccc")
  Boundary(group_1, "application", $tags="application") {
    Container(karpbackend.karpsearch, "karp.search", $techn="", $descr="Business logic around searching", $tags="", $link="")
    Container(karpbackend.karpauth, "karp.auth", $techn="", $descr="Business logic around authentication", $tags="", $link="")
    Container(karpbackend.karplex, "karp.lex", $techn="", $descr="Business logic around lexical resources and entries", $tags="", $link="")
  }

  AddBoundaryTag("infrastructure", $borderColor="#cccccc", $fontColor="#cccccc")
  Boundary(group_2, "infrastructure", $tags="infrastructure") {
    Container(karpbackend.karpauth_infrastructure, "karp.auth_infrastructure", $techn="Python and sb-auth", $descr="Concrete implementation of karp.auth business logic", $tags="", $link="")
    Container(karpbackend.karplex_infrastructure, "karp.lex_infrastructure", $techn="Python and relational database", $descr="Concrete implementation of karp.lex business logic", $tags="", $link="")
    Container(karpbackend.karpsearch_infrastructure, "karp.search_infrastructure", $techn="Python and database", $descr="Concrete implementation of karp.search business logic", $tags="", $link="")
    ContainerDb(karpbackend.MariaDB, "MariaDB", $techn="Relational database schema", $descr="", $tags="", $link="")
    ContainerDb(karpbackend.ElasticSearch, "ElasticSearch", $techn="Document database schema", $descr="", $tags="", $link="")
  }

  Container(karpbackend.karpmain, "karp.main", $techn="", $descr="Kernel connecting the generic business rules and the concrete implementations in infrastructure", $tags="", $link="")
  Container(karpbackend.WebAPI, "Web API", $techn="Python and FastAPI", $descr="Provides lexical and search functionality via a JSON API", $tags="", $link="")
  Container(karpbackend.karpcli, "karp-cli", $techn="Python and Typer", $descr="Provides admin tools for lexical resources via CLI", $tags="", $link="")
}

Rel_D(User, karpbackend.WebAPI, "Uses", $techn="", $tags="", $link="")
Rel_D(Machine, karpbackend.WebAPI, "Uses", $techn="", $tags="", $link="")
Rel_D(Admin, karpbackend.karpcli, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.WebAPI, karpbackend.karpauth, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.WebAPI, karpbackend.karplex, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.WebAPI, karpbackend.karpmain, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.WebAPI, karpbackend.karpsearch, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpcli, karpbackend.karplex, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpcli, karpbackend.karpmain, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpcli, karpbackend.karpsearch, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karplex, karplexcore, "", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpmain, karpbackend.karpauth_infrastructure, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpmain, karpbackend.karplex_infrastructure, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpmain, karpbackend.karpsearch_infrastructure, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpauth_infrastructure, karpbackend.karpauth, "Implements", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpauth_infrastructure, sbauth, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karplex_infrastructure, karpbackend.karplex, "Implements", $techn="", $tags="", $link="")
Rel_D(karpbackend.karplex_infrastructure, karpbackend.MariaDB, "Uses", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpsearch_infrastructure, karpbackend.karpsearch, "Implements", $techn="", $tags="", $link="")
Rel_D(karpbackend.karpsearch_infrastructure, karpbackend.ElasticSearch, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml