name: Coverage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  POETRY_VERSION: 1.3.1
  JUST_VERSION: "1.13.0"

jobs:
  coverage:
    name: Test coverage py-${{ matrix.python-version }} es-${{ matrix.es-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    services:
      mariadb:
        image: mariadb:10.3
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_DATABASE: karp
          MYSQL_PASSWORD: testing
          MYSQL_USER: karp
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        es-version: ["6.8.23"]
        os: [ubuntu-latest]

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v1
        with:
          just-version: ${{ env.JUST_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github/workflows/coverage.yml') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: just install-dev
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      # - name: Install library
      #   run: poetry install --no-interaction

      - name: Setup up environment
        run: cp -v .env.ci .env

      - name: Install Elasticsearch 6
        if: startsWith( matrix.es-version, '6')
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${{ matrix.es-version }}.tar.gz
          tar -xzf elasticsearch-${{ matrix.es-version }}.tar.gz
          ./elasticsearch-${{ matrix.es-version }}/bin/elasticsearch-plugin install analysis-icu
          echo "TEST_ELASTICSEARCH_ENABLED=True" >> .env
          echo "TEST_ES_HOME=`realpath elasticsearch-${{ matrix.es-version }}`" >> .env
          echo "SEARCH_CONTEXT=es6_search_service" >> .env
          cat .env
          # make install-dev-elasticsearch6
          # pip install -e .[elasticsearch6]

      - name: Install Elasticsearch 7
        if: startsWith( matrix.es-version, '7')
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${{ matrix.es-version }}-linux-x86_64.tar.gz
          tar -xzf elasticsearch-${{ matrix.es-version }}-linux-x86_64.tar.gz
          echo "TEST_ELASTICSEARCH_ENABLED=True" >> .env
          echo "TEST_ES_HOME=`realpath elasticsearch-${{ matrix.es-version }}`" >> .env
          cat .env
          pip install -e .[elasticsearch7]
      - name: Run all tests for coverage report
        run: just cov-report=xml all-tests-w-coverage
        env:
          DB_TEST_DATABASE: karp
          DB_USER: karp
          DB_PASSWORD: testing
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mariadb.ports['3306'] }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
