name: Code checks for karp-lex-core

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - v*
    paths:
      - 'karp-lex-core/**'
      - '!karp-lex-core/README.md'
  pull_request:
    branches:
      - "*"
    paths:
      - 'karp-lex-core/**'

env:
  POETRY_VERSION: 1.3.1
  JUST_VERSION: "1.13.0"

jobs:
  checks:
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
        task:
          - name: Lint code
            run: just karp-lex-core/lint
          - name: Typecheck
            run: just karp-lex-core/type-check
          - name: Check formatting
            run: just karp-lex-core/check-fmt

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Load cached $HOME/.local
      #   uses: actions/cache@v3.1.6
      #   with:
      #     path: ~/.local
      #     key: dotlocal-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('.github/workflows/build.yml') }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: karp-lex-core/.venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github/workflows/lex-core-checks.yml') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: just karp-lex-core/install-ci

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}

